#!/bin/bash

GET_URLS=(upcoming nextclash summoners/Starkiller645 summoners/SGB2006 recent bans picks)
echo -e "\033[1m\033[37m[lambtest]\033[0m Testing API endpoints on localhost:3080"
sleep 5 
for ep in "${GET_URLS[@]}"
do
	IDENT=$(tr "/" "." <<< ${ep})
	RES_CODE=$(http GET "localhost:3080/${ep}" --headers > temp_${IDENT}.txt; cat temp_${IDENT}.txt | head -n 1)
	if echo ${RES_CODE} | grep -q "HTTP/1.1 200 OK";
	then
		echo -e "\033[1m[/${ep}]\033[32m Passed!\033[0m"
		echo -e "\033[1m\033[36m${RES_CODE}\033[0m"
	else
		echo -e "\033[1m[/${ep}]\033[31m Failed!\033[0m"
		echo -e "\033[1m\033[91m${RES_CODE}\033[0m"
	fi
	find . -name "temp_*" -delete
done
echo -e "\033[1m\033[37m[lambtest]\033[0m Finished tests!"
